# Application Settings
spring.application.name=spendora-backend

# Database Configuration (Render PostgreSQL)
# IMPORTANT: Use the 'External Database URL' from Render. 
# It should look like: dpg-xxxx.oregon-postgres.render.com
spring.datasource.url=jdbc:postgresql://dpg-d6dg0o4tgctc73cde8mg-a.oregon-postgres.render.com/spendora_4nqp?sslmode=require
spring.datasource.username=spendora_user
spring.datasource.password=NWccAomzILCYLbtLE7t8XksPMW8oZbwj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
# Generate a secret key (Base64 or 32+ characters)
app.jwt.secret=spendora_secret_key_786c67315a6b5a454d4a413538426d4a6a3456726e6d306b
app.jwt.expiration-ms=86400000

# Email configurations (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=buildproject73@gmail.com
spring.mail.password=buildproject73
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


